### ISSUE TITLE
0_1data_formating从格式化暴露数据开始报错

### ISSUE THREAD

**Issue by aozaoa** [TullyMonster/MendelRookie#14]
你好 0_1data_formating运行时出现报错

从格式化暴露数据开始报错，以下是报错内容：
Formatted summary statistics will be saved to ==>  C:/Users/aozaoa/Desktop/testMR/output/#_FORMATED_DATA/BMI_ieu-a-2_formatted.csv.gz
Saving output messages to:
C:/Users/aozaoa/Desktop/testMR/output/#_FORMATED_DATA/BMI_ieu-a-2_formatted_log_msg.txt
Any runtime errors will be saved to:
C:/Users/aozaoa/Desktop/testMR/output/#_FORMATED_DATA/BMI_ieu-a-2_formatted_log_output.txt
Messages will not be printed to terminal.
Called from: value[[3L]](cond)
 
 Browse[1]> 
请问这是啥问题

**Comment by TullyMonster** [comment]
**这不是错误消息**，请仔细阅读这些控制台输出，它声明了：
1. 格式化后的 GWAS 文件输出位置；
2. 消息输出保存的位置；
3. 运行时产生错误后信息保存的位置。

请前往对应的位置查看具体内容。格式化过程相当耗时，请耐心等待执行完成。
