### ISSUE TITLE
bug? typo?

### ISSUE THREAD

**Issue by laleoarrow** [TullyMonster/MendelRookie#18]
`TwoSampleMR::get_r_from_bsen` return的是r2，为啥这里还要^2？
```
exposure_data$R2 <- TwoSampleMR::get_r_from_bsen(exposure_data$beta.exposure, exposure_data$se.exposure, exposure_data$samplesize.exposure)^2
```
以下`get_r_from_bsen`的源代码：
```
function (b, se, n) 
{
 Fval <- (b/se)^2
 R2 <- Fval/(n - 2 + Fval)
 return(sqrt(R2) * sign(b))
}
```

**Comment by TullyMonster** [comment]
显然，对于`TwoSampleMR::get_r_from_bsen()`函数，其逻辑为：
1. 计算 _F_ 统计量：$`F = \left(\frac{b}{se}\right)^2`$；
2. 计算$`R^2`$：$`R^2 = \frac{F}{n - 2 + F}`$；
3. 返回值为**相关系数** _r_，即基于 _b_ 符号的$`\sqrt{R^2}`$。

值得注意的是，我们所用的是**判定系数**$`R^2`$。

**Comment by laleoarrow** [comment]
感谢澄清
