### ISSUE TITLE
Env_initi的报错

### ISSUE THREAD

**Issue by xgxofdream** [TullyMonster/MendelRookie#2]
执行Env_initi时，提示：
`Skipping 9 packages not available: VariantAnnotation, SummarizedExperiment, S4Vectors, Rsamtools, IRanges, GenomicRanges, GenomeInfoDb, Biostrings, BiocGenerics`

**Comment by TullyMonster** [comment]
主要是 Bioconductor 的包。请尝试访问对应包的官网，下载后离线完成安装

**Comment by TullyMonster** [comment]
https://github.com/TullyMonster/MendelRookie/issues/1#issuecomment-2074519029

完成依赖的安装即可解决这个问题

**Comment by xgxofdream** [comment]
我把包下载到本地了，然后安装。安装的过程中，总是报错：
`Error in readRDS(file) : error reading from connection`
我尝试：重新启动RStudio后再安装，报错依旧。

大佬能提供一些解决思路吗，谢谢！

另外：你提到的：“完成依赖的安装” 是什么意思？谢谢。

**Comment by xgxofdream** [comment]
> 我把包下载到本地了，然后安装。安装的过程中，总是报错： `Error in readRDS(file) : error reading from connection` 我尝试：重新启动RStudio后再安装，报错依旧。
> 
> 大佬能提供一些解决思路吗，谢谢！
> 
> 另外：你提到的：“完成依赖的安装” 是什么意思？谢谢。

成功的解决办法：是要下载Binary格式的，而不是Source Package。

**Comment by TullyMonster** [comment]
> > 我把包下载到本地了，然后安装。安装的过程中，总是报错： `Error in readRDS(file) : error reading from connection` 我尝试：重新启动RStudio后再安装，报错依旧。
> > 
> > 大佬能提供一些解决思路吗，谢谢！
> > 
> > 另外：你提到的：“完成依赖的安装” 是什么意思？谢谢。
> 
> 成功的解决办法：是要下载Binary格式的，而不是Source Package。

恭喜！
