### ISSUE TITLE
哪里能找到FastTraitR和FastDownloader

### ISSUE THREAD

**Issue by xgxofdream** [TullyMonster/MendelRookie#6]
请问哪里能找到这两个包：

- [17] FastTraitR_1.0.0                        
- [18] FastDownloader_1.0.0               

运行 Evi_initi.R配置环境时，程序提示：

```
> install_if_not_installed("FastTraitR", FastDownloader::install_pkg("FastTraitR"))
Error in loadNamespace(x) : 不存在叫‘FastDownloader’这个名字的程辑包
Called from: doWithOneRestart(return(expr), restart)   
```  

```
Error in library(pkg, character.only = TRUE, quietly = TRUE) : 
  不存在叫‘FastDownloader’这个名字的程辑包
In addition: Warning messages:
1: In runHook(".onAttach", ns, dirname(nspath), nsname) :
  strings not representable in native encoding will be translated to UTF-8
2: In .chat_with_me_fun() :
  strings not representable in native encoding will be translated to UTF-8
Called from: library(pkg, character.only = TRUE, quietly = TRUE)
```

**Comment by TullyMonster** [comment]
> 请问哪里能找到这两个包：
> 
> - [17] FastTraitR_1.0.0                        
> - [18] FastDownloader_1.0.0               
> 
> 运行 Evi_initi.R配置环境时，程序提示：
> 
> ```
> > install_if_not_installed("FastTraitR", FastDownloader::install_pkg("FastTraitR"))
> Error in loadNamespace(x) : 不存在叫‘FastDownloader’这个名字的程辑包
> Called from: doWithOneRestart(return(expr), restart)   
> ```  
> 
> ```
> Error in library(pkg, character.only = TRUE, quietly = TRUE) : 
>   不存在叫‘FastDownloader’这个名字的程辑包
> In addition: Warning messages:
> 1: In runHook(".onAttach", ns, dirname(nspath), nsname) :
>   strings not representable in native encoding will be translated to UTF-8
> 2: In .chat_with_me_fun() :
>   strings not representable in native encoding will be translated to UTF-8
> Called from: library(pkg, character.only = TRUE, quietly = TRUE)
> ```

明天给你瞅瞅吧，要睡觉了

**Comment by xgxofdream** [comment]
> > 请问哪里能找到这两个包：
> > 
> > * [17] FastTraitR_1.0.0
> > * [18] FastDownloader_1.0.0
> > 
> > 运行 Evi_initi.R配置环境时，程序提示：
> > ```
> > > install_if_not_installed("FastTraitR", FastDownloader::install_pkg("FastTraitR"))
> > Error in loadNamespace(x) : 不存在叫‘FastDownloader’这个名字的程辑包
> > Called from: doWithOneRestart(return(expr), restart)   
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > Error in library(pkg, character.only = TRUE, quietly = TRUE) : 
> >   不存在叫‘FastDownloader’这个名字的程辑包
> > In addition: Warning messages:
> > 1: In runHook(".onAttach", ns, dirname(nspath), nsname) :
> >   strings not representable in native encoding will be translated to UTF-8
> > 2: In .chat_with_me_fun() :
> >   strings not representable in native encoding will be translated to UTF-8
> > Called from: library(pkg, character.only = TRUE, quietly = TRUE)
> > ```
> 
> 明天给你瞅瞅吧，要睡觉了

好的，谢谢啊！

**Comment by TullyMonster** [comment]
请参见 [ReadMe 文档](https://github.com/TullyMonster/MendelRookie?tab=readme-ov-file#%E8%8E%B7%E5%8F%96-fasttraitr-%E5%92%8C-fastdownloader-%E5%8C%85)获取帮助。
