### ISSUE TITLE
能否提供已经Formatted Data，这样你的教程就完备了。

### ISSUE THREAD

**Issue by xgxofdream** [TullyMonster/MendelRookie#7]
你好 Tully, 请问你能够上传已经经过 0_1data_formating处理好的SNP数据。这样你的这个教程就完美啦。因为有些朋友会因为电脑条件限制，拿不到Formatted Data，进而不能往下一步走了。

ps. 有什么在线工具，可以做0_1data_formating这一步吗？

谢谢了！

**Comment by TullyMonster** [comment]
你好！

客观上可以提供已完成格式化了的数据，但不建议。因为真实场景下，格式化的需求存在差异，本项目只给出将原始 GWAS 数据格式化的一般化方法。若电脑性能较弱，可以减小格式化时并行的线程数（[`nThread = 4`](https://github.com/TullyMonster/MendelRookie/blob/911843b02841d680da5c12bf5290cfddb66c19d7/0_1data_formating.R#L45)），但这会延长执行耗时。
> GWAS 原始数据格式化的过程，本质是规范 `SNPs` 的 rsid 标识并校验等。应该有在线服务可替代这个过程，但生成的数据未必能直接用于本项目的后续处理。
