### ISSUE TITLE
报错@2_Linkage_disequilibrium_analysis.R: Error in get_plink_exe() : could not find function "get_plink_exe"

### ISSUE THREAD

**Issue by xgxofdream** [TullyMonster/MendelRookie#9]
执行LD分析时，报错：Error in get_plink_exe() : could not find function "get_plink_exe"。
我想找个报错和没有安装上包FastTraitR_1.0.0有关吧？

报错细节：
```
> # ---去除连锁不平衡的 SNP 并保存
> unclump_snps <- ieugwasr::ld_clump(dat = dplyr::tibble(rsid = exposure_data$SNP, pval = exposure_data$pval.exposure, id = exposure_data$id.exposure),
+                                    clump_kb = CLUMP_KB,
+                                    clump_r2 = CLUMP_R2,
+                                    plink_bin = get_plink_exe(),
+                                    bfile = file.path(LD_REF, EXPOSURE_POP))
Clumping 6t7pnM, 1384 variants, using EUR population reference
Error in get_plink_exe() : could not find function "get_plink_exe"
Error during wrapup: 'length = 4' in coercion to 'logical(1)'
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
> exposure_data <- exposure_data %>%
+   dplyr::inner_join(unclump_snps, by = c("SNP" = "rsid")) %>%
+   dplyr::select(names(.))
Error in exposure_data %>% dplyr::inner_join(unclump_snps, by = c(SNP = "rsid")) %>%  : 
  could not find function "%>%"
> print(paste("剩余", nrow(exposure_data), "个 SNP"))
[1] "剩余 1384 个 SNP"
> write.csv(exposure_data, file = "exposure.LD.csv", row.names = FALSE); file.create(paste0("exposure.LD.csv - ", CLUMP_KB, " kb, ", CLUMP_R2, "R²"))
[1] TRUE
> 
> rm(list = setdiff(ls(), GLOBAL_VAR))  # 移除无用的变量
> 
```

**Comment by xgxofdream** [comment]
> 是的

你能从你本地找到这个包，发给我吗...感谢！我在网上找不到。

**Comment by TullyMonster** [comment]
> > 是的
> 
> 你能从你本地找到这个包，发给我吗...感谢！我在网上找不到。

https://m.bilibili.com/video/BV1Uu4m1g7np

**Comment by xgxofdream** [comment]
> > > 是的
> > 
> > 
> > 你能从你本地找到这个包，发给我吗...感谢！我在网上找不到。
> 
> https://m.bilibili.com/video/BV1Uu4m1g7np

成功装上FastTraitR_1.0.0，执行2_Linkage_disequilibrium_analysis.R，相同的报错出现了...哎

**Comment by xgxofdream** [comment]
> > > > 是的
> > > 
> > > 
> > > 你能从你本地找到这个包，发给我吗...感谢！我在网上找不到。
> > 
> > 
> > https://m.bilibili.com/video/BV1Uu4m1g7np
> 
> 成功装上FastTraitR_1.0.0，执行2_Linkage_disequilibrium_analysis.R，相同的报错出现了...哎
> 
> 我查看了这个包的文档。确实没有函数：get_plink_exe....

原因是 ieugwasr 这个包，而不是FastTraitR。你的ieugwasr的版本是0.2.2-9000，而我的是1.0.0. ieugwasr@1.0.0里面确实没有函数get_plink_exe().

所有我干脆把plink_bin 指定为：NULL
`plink_bin = NULL`

请问plink_bin 是指的什么？

**Comment by shiningflashZZY** [comment]
首先下载PLINK，可以把压缩包里的PLINK.EXE解压到R语言安装位置的BIN文件夹里，然后把那个get_plink_exe()替换成plink.exe的位置路径，我的是"D:/R-4.4.1/bin/plink.exe"。亲测有用
